version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes: 
      - dbdata:/var/lib/postgresql/data
  my-go-app3:
    container_name: my-go-app3
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./templates:/app/templates
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=myappdb
    depends_on:
      - "postgres"
volumes:
  dbdata: